version: "2"
services:
  funmap:
    container_name: funmap
    image: funmap:latest
    shm_size: '50gb'
    volumes:
      - ./data:/data
      - ./results/:/results
      - ./mappings:/mappings
  mysql:
    container_name: mysql
    image: mysql:8.0
    shm_size: '50gb'
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"